=== Bernardo-MG/Tabletop-Dice-Java/src/test/resources/parameter/dice.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="test_data">
		<xs:complexType>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element name="data" type="dice" />
			</xs:sequence>
		</xs:complexType>
		<xs:unique name="uniqueData">
			<xs:selector xpath="data" />
			<xs:field xpath="sides" />
			<xs:field xpath="quantity" />
			<xs:field xpath="modifier" />
		</xs:unique>
	</xs:element>

	<xs:complexType name="dice">
		<xs:sequence>
			<xs:element name="sides" type="xs:integer" maxOccurs="1"
				minOccurs="1" />
			<xs:element name="quantity" type="xs:integer" maxOccurs="1" />
			<xs:element name="modifier" type="xs:integer" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>

</xs:schema>

=== Bernardo-MG/Tabletop-Dice-Java/src/test/resources/parameter/dice.xml
<?xml version="1.0" encoding="UTF-8"?>
<test_data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="dice.xsd">
	<data>
		<sides>1</sides>
		<quantity>0</quantity>
		<modifier>0</modifier>
	</data>
	<data>
		<sides>1</sides>
		<quantity>1</quantity>
		<modifier>0</modifier>
	</data>
	<data>
		<sides>1</sides>
		<quantity>1</quantity>
		<modifier>1</modifier>
	</data>
	<data>
		<sides>1</sides>
		<quantity>1</quantity>
		<modifier>5</modifier>
	</data>
	<data>
		<sides>1</sides>
		<quantity>5</quantity>
		<modifier>0</modifier>
	</data>
	<data>
		<sides>1</sides>
		<quantity>5</quantity>
		<modifier>1</modifier>
	</data>
	<data>
		<sides>1</sides>
		<quantity>5</quantity>
		<modifier>5</modifier>
	</data>
	<data>
		<sides>6</sides>
		<quantity>1</quantity>
		<modifier>0</modifier>
	</data>
	<data>
		<sides>6</sides>
		<quantity>0</quantity>
		<modifier>0</modifier>
	</data>
	<data>
		<sides>6</sides>
		<quantity>1</quantity>
		<modifier>1</modifier>
	</data>
	<data>
		<sides>6</sides>
		<quantity>1</quantity>
		<modifier>3</modifier>
	</data>
	<data>
		<sides>6</sides>
		<quantity>10</quantity>
		<modifier>0</modifier>
	</data>
	<data>
		<sides>6</sides>
		<quantity>10</quantity>
		<modifier>1</modifier>
	</data>
	<data>
		<sides>6</sides>
		<quantity>10</quantity>
		<modifier>3</modifier>
	</data>
	<data>
		<sides>20</sides>
		<quantity>1</quantity>
		<modifier>0</modifier>
	</data>
	<data>
		<sides>20</sides>
		<quantity>0</quantity>
		<modifier>0</modifier>
	</data>
	<data>
		<sides>20</sides>
		<quantity>1</quantity>
		<modifier>1</modifier>
	</data>
	<data>
		<sides>20</sides>
		<quantity>1</quantity>
		<modifier>3</modifier>
	</data>
	<data>
		<sides>20</sides>
		<quantity>10</quantity>
		<modifier>0</modifier>
	</data>
	<data>
		<sides>20</sides>
		<quantity>10</quantity>
		<modifier>1</modifier>
	</data>
	<data>
		<sides>20</sides>
		<quantity>10</quantity>
		<modifier>3</modifier>
	</data>
	<data>
		<sides>100</sides>
		<quantity>1</quantity>
		<modifier>0</modifier>
	</data>
	<data>
		<sides>100</sides>
		<quantity>0</quantity>
		<modifier>0</modifier>
	</data>
	<data>
		<sides>100</sides>
		<quantity>1</quantity>
		<modifier>1</modifier>
	</data>
	<data>
		<sides>100</sides>
		<quantity>1</quantity>
		<modifier>3</modifier>
	</data>
	<data>
		<sides>100</sides>
		<quantity>10</quantity>
		<modifier>0</modifier>
	</data>
	<data>
		<sides>100</sides>
		<quantity>10</quantity>
		<modifier>1</modifier>
	</data>
	<data>
		<sides>100</sides>
		<quantity>10</quantity>
		<modifier>3</modifier>
	</data>
	<data>
		<sides>2147483647</sides>
		<quantity>1</quantity>
		<modifier>0</modifier>
	</data>
	<data>
		<sides>2147483647</sides>
		<quantity>20</quantity>
		<modifier>10</modifier>
	</data>
	<data>
		<sides>2147483647</sides>
		<quantity>20</quantity>
		<modifier>2147483647</modifier>
	</data>
</test_data>
