=== Bernardo-MG/Tabletop-Dice-Java/src/test/resources/parameter/dice-text.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="test_data">
		<xs:complexType>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element name="data" type="dice" />
			</xs:sequence>
		</xs:complexType>
		<xs:unique name="uniqueData">
			<xs:selector xpath="data" />
			<xs:field xpath="text" />
		</xs:unique>
	</xs:element>

	<xs:complexType name="dice">
		<xs:sequence>
			<xs:element name="text" type="xs:string" />
			<xs:element name="sides" type="xs:integer" />
			<xs:element name="quantity" type="xs:integer" />
		</xs:sequence>
	</xs:complexType>

</xs:schema>

=== Bernardo-MG/Tabletop-Dice-Java/src/test/resources/parameter/dice-text.xml
<?xml version="1.0" encoding="UTF-8"?>
<test_data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="dice-text.xsd">
	<data>
		<text>0d1</text>
		<sides>1</sides>
		<quantity>0</quantity>
	</data>
	<data>
		<text>1d1</text>
		<sides>1</sides>
		<quantity>1</quantity>
	</data>
	<data>
		<text>1d6</text>
		<sides>6</sides>
		<quantity>1</quantity>
	</data>
	<data>
		<text>6d6</text>
		<sides>6</sides>
		<quantity>6</quantity>
	</data>
	<data>
		<text>2147483647d2147483647</text>
		<sides>2147483647</sides>
		<quantity>2147483647</quantity>
	</data>
</test_data>
