=== Bernardo-MG/Tabletop-Dice-Java/src/test/resources/parameter/function-extremes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="test_data">
		<xs:complexType>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element name="data" type="values" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="values">
		<xs:sequence>
			<xs:element name="count" type="xs:integer" maxOccurs="1"
				minOccurs="1" />
			<xs:element name="rolls" type="rolls" maxOccurs="1"
				minOccurs="1" />
			<xs:element name="results" type="results" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="rolls">
		<xs:sequence minOccurs="1" maxOccurs="unbounded">
			<xs:element name="roll" type="xs:integer" maxOccurs="1"
				minOccurs="1" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="results">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element name="result" type="xs:integer" maxOccurs="1"
				minOccurs="1" />
		</xs:sequence>
	</xs:complexType>

</xs:schema>

=== Bernardo-MG/Tabletop-Dice-Java/src/test/resources/parameter/function-extremes-keep-lowest.xml
<?xml version="1.0" encoding="UTF-8"?>
<test_data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="function-extremes.xsd">
	<data>
		<count>5</count>
		<rolls>
			<roll>1</roll>
			<roll>6</roll>
			<roll>3</roll>
			<roll>3</roll>
			<roll>3</roll>
		</rolls>
		<results>
			<result>1</result>
			<result>6</result>
			<result>3</result>
			<result>3</result>
			<result>3</result>
		</results>
	</data>
	<data>
		<count>3</count>
		<rolls>
			<roll>1</roll>
			<roll>6</roll>
			<roll>3</roll>
			<roll>3</roll>
			<roll>3</roll>
		</rolls>
		<results>
			<result>1</result>
			<result>3</result>
			<result>3</result>
		</results>
	</data>
	<data>
		<count>3</count>
		<rolls>
			<roll>6</roll>
			<roll>3</roll>
			<roll>3</roll>
			<roll>3</roll>
			<roll>1</roll>
		</rolls>
		<results>
			<result>3</result>
			<result>3</result>
			<result>1</result>
		</results>
	</data>
</test_data>
